[package]
name    = "a_plus_b"
version = "0.1.0"
edition = "2024"

[lints.rust]
unused_imports = "allow"

[dependencies]
indoc   = { version = "2.0.6" }
dmoj    = { version = "0.1.5" }

[dev-dependencies]
assert_cmd  = { version = "2.0.17" }
